% R bootcamp, Schedule
% August 2019, UC Berkeley
% Chris Paciorek

# Schedule

- Day 1 morning (8:30-12:15) (learning R)

  - Module 0: Introduction, what is R, starting R, why R? why not R? (Chris) (15 minutes)
  - Module 1: Basics of R, with Rstudio (Chris)
<details>
      <summary>Click to expand</summary>

      - R as a calculator
      - helpful shortcuts: tab-complete, up arrow, Ctrl-{up arrow}
      - vectors and indexing and subset assignment
</details>

<details>
  - <summary>Module 2: Basics of R, with Rstudio (Chris)</summary>

      - R as a calculator
      - helpful shortcuts: tab-complete, up arrow, Ctrl-{up arrow}
      - vectors and indexing and subset assignment
</details>


# Schedule

Day 1 morning (8:30-12:15) (learning R)

- <details>
  <summary>Module 0 (click for details)</summary>
  
      - R as a calculator
      - helpful shortcuts: tab-complete, up arrow, Ctrl-{up arrow}
      - vectors and indexing and subset assignment
</details>

- <details>
  <summary>Module 1 (click for details)</summary>
  
      - R as a calculator
      - helpful shortcuts: tab-complete, up arrow, Ctrl-{up arrow}
      - vectors and indexing and subset assignment
</details>
